config/routes.rb
Rails.application.routes.draw do
  resources :managers

  resources :sales

  resources :inventories

  resources :finances

  resources :owners

  devise_for :people
  root 'inventories#index.html.haml'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
  has_many :sales

  def self.calculate_quote_table(quote = 0,year = 0,tax = 0)
    Rails.logger.debug "Inputs: #{quote} #{year} #{tax}"
    quote = []
    (0..year).each do |t|
      quote << quote * Math.exp(tax * t)
    end
    return quote
  end

  def calculate_quote_table
    return self.class.calculate_quote_table(self.quote,self.year,self.tax)
  end

end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @calculate_tax = @finance.calculate_tax_table
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def quote
    rate = params[:rate]
    time = params[:time]
    initial_quote = params[:pop]
    @quote_array = taxCalculator.calculate_quote_table(initial_quote.to_i, time.to_i, rate.to_f)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:finance_quote, :tax, :year)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_finance_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Year</th>
  <th>tax</th>
  <% @tax_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n %></td>
        <td><%= p.round(2) %></td>
      </tr>
  <% end %>

</table>

app/views/finances/_form.html.erb
<%= simple_form_for(@finance) do |f| %>
    <% if @finance.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being
            saved:</h2>

          <ul>
            <% @finance.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :finance_quote %><br>
      <%= f.number_field :finance_quote %>
    </div>
    <div class="field">
      <%= f.label :tax %><br>
      <%= f.text_field :tax %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.number_field :year %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<div id="finance-table" class="table-format"></div>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/finance.js.erb
$('#tax-table').html("<%= j (render 'finance_table') %>")

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Finances</h1>

<table>
  <thead>
    <tr>
      <th>Finance quote</th>
      <th>Tax</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.finance_quote %></td>
        <td><%= finance.tax %></td>
        <td><%= finance.year %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %><br>
<%= link_to 'Main Menu', root_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Finance quote:</strong>
  <%= @finance.finance_quote %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @finance.tax %>
</p>

<p>
  <strong>Year:</strong>
  <%= @finance.year %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>