config/routes.rb
Rails.application.routes.draw do
  resources :managers

  resources :sales

  resources :inventories

  resources :finances

  resources :owners

  devise_for :people
  root 'inventories#index.html.haml'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :sale


end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:model, :color, :price, :vin)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= simple_form_for(@inventory) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :model %>
    <%= f.input :color %>
    <%= f.input :price %>
    <%= f.input :vin %>
  </div>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Color</th>
      <th>Price</th>
      <th>Vin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.model %></td>
        <td><%= inventory.color %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.vin %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %><br>
<%= link_to 'Main Menu', root_path %>

app/views/inventories/index.html.haml
%h Hello, what type of user are you?
<br>
= link_to 'Sales', sales_path
<br>
= link_to 'Sales Manager', managers_path
<br>
= link_to 'Inventory Management', inventories_path
<br>
= link_to 'Finances', finances_path
<br>
= link_to 'Dealership Owner', owners_path

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @inventory.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @inventory.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @inventory.vin %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>