config/routes.rb
Rails.application.routes.draw do
  resources :managers

  resources :sales

  resources :inventories

  resources :finances

  resources :owners

  devise_for :people
  root 'inventories#index.html.haml'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  belongs_to :sale
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:employee_name, :sale_id)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= simple_form_for(@manager) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :employee_name %>

  </div>

    <div class="field">

      <%= f.label :Customer %><br>
      <%= f.collection_select :sale_id, Sale.all, :id, :customer ,{:multiple => false}%><br>

      <%= f.label :Sold %><br>
      <%= f.collection_select :sale_id, Sale.all, :id, :sold ,{:multiple => true}%><br>

      <%= f.label :Quote %><br>
      <%= f.collection_select :sale_id, Sale.all, :id, :quote ,{:multiple => false}%><br>



    </div>


    <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Managers</h1>

<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Customer Name</th>
      <th>Sold</th>
      <th>Quote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.employee_name %></td>
        <td><%= manager.sale.customer %></td>
        <td><%= manager.sale.sold %></td>
        <td><%= manager.sale.quote %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %><br>
<%= link_to 'Main Menu', root_path %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee name:</strong>
  <%= @manager.employee_name %>
</p>


<p>
  <strong>Customer:</strong>
  <%= @manager.sale.customer %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @manager.sale.sold %>
</p>

<p>
  <strong>quote:</strong>
  <%= @manager.sale.quote %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>