config/routes.rb
Rails.application.routes.draw do
  resources :managers

  resources :sales

  resources :inventories

  resources :finances

  resources :owners

  devise_for :people
  root 'inventories#index.html.haml'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :inventory
  has_many :manager
  def self.search(search)
    if search
      self.where('name LIKE ?', "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]


  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show

  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def index
    @sales = Sale.search(params[:search])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer, :quote, :sold, :sale_id, :inventory_id)
    end
    end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :customer %>
    <%= f.input :quote %>
    <%= f.label :Sold %>
    <%= f.select(:sold, ['Yes','No']) %>
  </div>

    <div class="field">

      <%= f.label :Model %><br>
      <%= f.collection_select :inventory_id, Inventory.all, :id, :model ,{:multiple => false}%><br>
      <%= f.label :Color %><br>
      <%= f.collection_select :inventory_id, Inventory.all, :id, :color ,{:multiple => false} %><br>
      <%= f.label :price %><br>
      <%= f.collection_select :inventory_id, Inventory.all, :id, :price ,{:multiple => false} %><br>
      <%= f.label :VIN %><br>
      <%= f.collection_select :inventory_id, Inventory.all, :id, :vin ,{:multiple => false}%><br>





    </div>




  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>


<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Quote</th>
      <th>Sold</th>
      <th>Model</th>
      <th>Color</th>
      <th>Price</th>
      <th>VIN</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.customer %></td>
        <td><%= sale.quote %></td>
        <td><%= sale.sold %></td>
        <td><%= sale.inventory.model %></td>
        <td><%= sale.inventory.color %></td>
        <td><%= sale.inventory.price %></td>
        <td><%= sale.inventory.vin %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>




        <%= form_tag sales_path, :method => 'get' do %>
            <p>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :model => nil %>
            </p>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %><br>
<%= link_to 'Main Menu', root_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @sale.sold %>
</p>

<p>
  <strong>Model:</strong>
  <%= @sale.inventory.model %>
</p>
<p>
  <strong>Color:</strong>
  <%= @sale.inventory.color %>
</p>
<p>
  <strong>Price:</strong>
  <%= @sale.inventory.price %>
</p>
<p>
  <strong>VIN:</strong>
  <%= @sale.inventory.vin %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>